### ISSUE TITLE
Priority One

### ISSUE THREAD

**Issue by owy1** [Woojgh/DNA#3]
general: docstrings, test_modulename.py

- Sean
build a pyramid model interface with postgres XXX
construct pyramid routes XXX
build a program that finds insertion mutations

- Ophelia
build jinja2 templates (index, about, display)
adding security to pyramid (token session) XXX
build a program that finds substitution mutations
develop heat map with matplotlib XXX

- Erik
create cookie cutter template, setup and tox.ini (then ACP so everyone can pull to their locals) XXX
heroku deploymen XXX
build a program that finds inversion mutations

- James
create postgres database XXX
create pyramid views (index, about, display) XXX
build a program that finds deletion mutations

**Comment by Woojgh** [comment]
We have all of the single issues done.
